application: webrtc-experiment
version: 1
runtime: python27
api_version: 1
threadsafe: yes
default_expiration: "1h"

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /robots\.txt
  static_files: robots.txt
  upload: robots\.txt

- url: /(.*\.(js|css))
  static_files: files/\1
  upload: files/(.*\.(js|css))

- url: /demos/(.*\.(html))
  static_files: files/demos/\1
  upload: files/demos/(.*\.(html))
  
- url: /docs/(.*\.(html))
  static_files: files/docs/\1
  upload: files/docs/(.*\.(html))

- url: /images
  static_dir: images

- url: /googlea39ddc1167f80053\.html
  static_files: googlea39ddc1167f80053.html
  upload: googlea39ddc1167f80053\.html  

- url: .*
  script: main.app
  secure: always

libraries:
- name: webapp2
  version: "2.5.1"
